#!/bin/bash

# From https://www.linuxjournal.com/content/validating-ip-address-bash-script
# Test an IP address for validity:
# Usage:
#      valid_ip IP_ADDRESS
#      if [[ $? -eq 0 ]]; then echo good; else echo bad; fi
#   OR
#      if valid_ip IP_ADDRESS; then echo good; else echo bad; fi
#
function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}



# read old ip address if file exists
filename="./external_ip.txt"
if test -f "$filename"; then
  read -d $'\x04' old_ip < "$filename"
else
  old_ip="not set"
fi
echo "old_ip: "$old_ip

# get current ip address from three different sources
echo "responses ..."
new_ip1=$(curl -s ifconfig.me --stderr -)
echo "ifconfig.me: "$new_ip1
#new_ip2=$(dig +short myip.opendns.com @resolver1.opendns.com)
#echo "myip.opendns.com: "$new_ip2
new_ip2=$(curl -s ipinfo.io/ip --stderr -)
echo "ipinfo.io/ip: "$new_ip2
new_ip3=$(curl -s icanhazip.com --stderr -)
echo "icanhazip.com: "$new_ip3

# test ip address has changed -- if at least one source matches old address then assume no change
if [[ $old_ip == $new_ip1 || $old_ip == $new_ip2 || $old_ip == $new_ip3 ]]; then
  echo "EXTERNAL IP SAME"
  final_ip="$old_ip"
else
  echo "EXTERNAL IP CHANGED"
  if valid_ip $new_ip1 && [[ $new_ip1 == $new_ip2 ]]; then
    final_ip="$new_ip1"
  elif valid_ip $new_ip2 && [[ $new_ip2 == $new_ip3 ]]; then
    final_ip="$new_ip2"
  elif valid_ip $new_ip3 && [[ $new_ip3 == $new_ip1 ]]; then
    final_ip="$new_ip3"
  else
    echo "No two are the same"
    if valid_ip $new_ip1 && ! valid_ip $new_ip2 && ! valid_ip $new_ip3; then
      final_ip="$new_ip1"
    elif ! valid_ip $new_ip1 && valid_ip $new_ip2 && ! valid_ip $new_ip3; then
      final_ip="$new_ip2"
    elif ! valid_ip $new_ip1 && ! valid_ip $new_ip2 && valid_ip $new_ip3; then
      final_ip="$new_ip3"
    else
      echo "EXTERNAL IP SAME"
      final_ip="$old_ip"
    fi
  fi
fi 

if [[ ! $old_ip == $final_ip ]]; then
  echo "OVERWRITING $filename"
  echo "$final_ip" > "$filename"
  exit 1
fi
exit 0

